#############################################################################
# Makefile for building: wordpress-viewer
# Generated by qmake (2.01a) (Qt 4.8.3) on: Wed Mar 27 11:02:41 2013
# Project:  wordpress-viewer.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile wordpress-viewer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDEPLOYMENT_PATH="\""/opt/sdk/share/wordpress-viewer/"\"" -DHAS_BOOSTER -DQT_SHARED -DQT_DECLARATIVE_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -Isailfishapplication -I/usr/include/qt4 -I/usr/include/applauncherd -Imoc
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lqjson -pie -rdynamic -lmdeclarativecache -lQtDeclarative -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		author.cpp \
		post.cpp \
		sharedobjectspool.cpp \
		postmodel.cpp \
		posthelper.cpp \
		sailfishapplication/sailfishapplication.cpp moc/moc_author.cpp \
		moc/moc_post.cpp \
		moc/moc_sharedobjectspool.cpp \
		moc/moc_postmodel.cpp \
		moc/moc_posthelper.cpp
OBJECTS       = obj/main.o \
		obj/author.o \
		obj/post.o \
		obj/sharedobjectspool.o \
		obj/postmodel.o \
		obj/posthelper.o \
		obj/sailfishapplication.o \
		obj/moc_author.o \
		obj/moc_post.o \
		obj/moc_sharedobjectspool.o \
		obj/moc_postmodel.o \
		obj/moc_posthelper.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		sailfishapplication/sailfishapplication.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		wordpress-viewer.pro
QMAKE_TARGET  = wordpress-viewer
DESTDIR       = 
TARGET        = wordpress-viewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: wordpress-viewer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		sailfishapplication/sailfishapplication.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtDeclarative.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile wordpress-viewer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
sailfishapplication/sailfishapplication.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtCore.prl:
/usr/lib/libQtDeclarative.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile wordpress-viewer.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/wordpress-viewer1.0.0 || $(MKDIR) obj/wordpress-viewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/wordpress-viewer1.0.0/ && $(COPY_FILE) --parents jsonhelper_p.h datetimeformat_p.h author.h post.h sharedobjectspool.h postmodel.h posthelper.h sailfishapplication/sailfishapplication.h obj/wordpress-viewer1.0.0/ && $(COPY_FILE) --parents main.cpp author.cpp post.cpp sharedobjectspool.cpp postmodel.cpp posthelper.cpp sailfishapplication/sailfishapplication.cpp obj/wordpress-viewer1.0.0/ && (cd `dirname obj/wordpress-viewer1.0.0` && $(TAR) wordpress-viewer1.0.0.tar wordpress-viewer1.0.0 && $(COMPRESS) wordpress-viewer1.0.0.tar) && $(MOVE) `dirname obj/wordpress-viewer1.0.0`/wordpress-viewer1.0.0.tar.gz . && $(DEL_FILE) -r obj/wordpress-viewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_author.cpp moc/moc_post.cpp moc/moc_sharedobjectspool.cpp moc/moc_postmodel.cpp moc/moc_posthelper.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_author.cpp moc/moc_post.cpp moc/moc_sharedobjectspool.cpp moc/moc_postmodel.cpp moc/moc_posthelper.cpp
moc/moc_author.cpp: jsonhelper_p.h \
		author.h
	/usr/bin/moc $(DEFINES) $(INCPATH) author.h -o moc/moc_author.cpp

moc/moc_post.cpp: author.h \
		jsonhelper_p.h \
		post.h
	/usr/bin/moc $(DEFINES) $(INCPATH) post.h -o moc/moc_post.cpp

moc/moc_sharedobjectspool.cpp: author.h \
		jsonhelper_p.h \
		sharedobjectspool.h
	/usr/bin/moc $(DEFINES) $(INCPATH) sharedobjectspool.h -o moc/moc_sharedobjectspool.cpp

moc/moc_postmodel.cpp: postmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) postmodel.h -o moc/moc_postmodel.cpp

moc/moc_posthelper.cpp: posthelper.h
	/usr/bin/moc $(DEFINES) $(INCPATH) posthelper.h -o moc/moc_posthelper.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: main.cpp author.h \
		jsonhelper_p.h \
		post.h \
		postmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/author.o: author.cpp author.h \
		jsonhelper_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/author.o author.cpp

obj/post.o: post.cpp post.h \
		author.h \
		jsonhelper_p.h \
		sharedobjectspool.h \
		datetimeformat_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/post.o post.cpp

obj/sharedobjectspool.o: sharedobjectspool.cpp sharedobjectspool.h \
		author.h \
		jsonhelper_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sharedobjectspool.o sharedobjectspool.cpp

obj/postmodel.o: postmodel.cpp postmodel.h \
		post.h \
		author.h \
		jsonhelper_p.h \
		sharedobjectspool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/postmodel.o postmodel.cpp

obj/posthelper.o: posthelper.cpp posthelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/posthelper.o posthelper.cpp

obj/sailfishapplication.o: sailfishapplication/sailfishapplication.cpp sailfishapplication/sailfishapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sailfishapplication.o sailfishapplication/sailfishapplication.cpp

obj/moc_author.o: moc/moc_author.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_author.o moc/moc_author.cpp

obj/moc_post.o: moc/moc_post.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_post.o moc/moc_post.cpp

obj/moc_sharedobjectspool.o: moc/moc_sharedobjectspool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_sharedobjectspool.o moc/moc_sharedobjectspool.cpp

obj/moc_postmodel.o: moc/moc_postmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_postmodel.o moc/moc_postmodel.cpp

obj/moc_posthelper.o: moc/moc_posthelper.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_posthelper.o moc/moc_posthelper.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/sdk/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/sdk/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/sdk/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/sdk/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/sdk/bin/ 


install_qml: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/ || $(MKDIR) $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/ 
	-$(INSTALL_PROGRAM) /home/mersdk/wordpress-viewer/main.qml $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/
	-$(INSTALL_DIR) /home/mersdk/wordpress-viewer/pages $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/
	-$(INSTALL_DIR) /home/mersdk/wordpress-viewer/cover $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/
	-$(INSTALL_PROGRAM) /home/mersdk/wordpress-viewer/main.qml $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/


uninstall_qml:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/main.qml 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/pages 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/cover 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/main.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/sdk/share/wordpress-viewer/ 


install:  install_target install_qml  FORCE

uninstall: uninstall_target uninstall_qml   FORCE

FORCE:

